Document: rainbowcrack
Title: Debian rainbowcrack Manual
Author: <insert document author here>
Abstract: This manual describes what rainbowcrack is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/rainbowcrack/rainbowcrack.sgml.gz

Format: postscript
Files: /usr/share/doc/rainbowcrack/rainbowcrack.ps.gz

Format: text
Files: /usr/share/doc/rainbowcrack/rainbowcrack.text.gz

Format: HTML
Index: /usr/share/doc/rainbowcrack/html/index.html
Files: /usr/share/doc/rainbowcrack/html/*.html
